// Generated by Candypad Configurator
#pragma once

// Layers
#define DYNAMIC_KEYMAP_LAYER_COUNT 4

// OLED
#define OLED_TIMEOUT 60000  // 60 s idle off
#define OLED_BRIGHTNESS 128

// Encoders
#define ENCODER_DEFAULT_POS 0x3  // 1:1 resolution
