// ============================================================
// Candypad QMK Keymap — generated by Candypad Configurator
// Flash with:  qmk compile -kb binepad/candypad -km my_keymap
// Docs: https://docs.qmk.fm
// ============================================================

#include QMK_KEYBOARD_H

// ── Layer indices ─────────────────────────────────────────
enum layers {
    _BASE = 0,
    _FN,
    _LAYER2,
    _LAYER3,
};

// ── Keymaps ───────────────────────────────────────────────
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_BASE] = LAYOUT(
        KC_MUTE, KC_BTN3,
        KC_NUM, KC_PSLS, KC_PAST, KC_PMNS,
        KC_P7, KC_P8, KC_P9, KC_PPLS,
        KC_P4, KC_P5, KC_P6,
        KC_P1, KC_P2, KC_P3, KC_PENT,
        KC_P0,           KC_PDOT
    ),

    [_FN] = LAYOUT(
        KC_TRNS, KC_TRNS,
        MO(1), KC_F1, KC_F2, RGB_TOG,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    ),

    [_LAYER2] = LAYOUT(
        KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    ),

    [_LAYER3] = LAYOUT(
        KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    )
};


#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [_BASE] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(MS_WHLU, MS_WHLD) },
    [_FN] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
    [_LAYER2] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
    [_LAYER3] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) }
};
#endif





// ── Bongo Cat Animation ─────────────────────────────────
static uint32_t bongo_timer = 0;
static bool bongo_tapping = false;

void render_bongo_cat(void) {
    if (bongo_tapping && timer_elapsed32(bongo_timer) > 200) {
        bongo_tapping = false;
    }

    oled_clear();

    if (bongo_tapping) {
        // Tap frame — paws down
        oled_set_cursor(6, 0);
        oled_write_P(PSTR("/\\_/\\"), false);
        oled_set_cursor(5, 1);
        oled_write_P(PSTR("( o.o )"), false);
        oled_set_cursor(5, 2);
        oled_write_P(PSTR(" > ^ < "), false);
        oled_set_cursor(4, 3);
        oled_write_P(PSTR("/|") , false);
        oled_set_cursor(13, 3);
        oled_write_P(PSTR("|\\") , false);
    } else {
        // Idle frame — paws up
        oled_set_cursor(6, 0);
        oled_write_P(PSTR("/\\_/\\"), false);
        oled_set_cursor(5, 1);
        oled_write_P(PSTR("( -.- )"), false);
        oled_set_cursor(5, 2);
        oled_write_P(PSTR(" > ^ <"), false);
        oled_set_cursor(5, 3);
        oled_write_P(PSTR("  /_/"), false);
    }

    // WPM counter on the right side
    oled_set_cursor(16, 1);
    oled_write_P(PSTR("WPM"), false);
    oled_set_cursor(16, 2);
    char wpm_str[4];
    itoa(get_current_wpm(), wpm_str, 10);
    oled_write(wpm_str, true);
}

void bongo_cat_tap(void) {
    bongo_tapping = true;
    bongo_timer = timer_read32();
}


oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    return OLED_ROTATION_0;
}

bool oled_task_user(void) {
    render_bongo_cat();
    return false; // true = let board render default dashboard, false = we handled it ourselves
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (record->event.pressed) {
        bongo_cat_tap();
    }
    return true;
}


