// ============================================================
// Candypad QMK Keymap — generated by Candypad Configurator
// Flash with:  qmk compile -kb binepad/candypad -km my_keymap
// Docs: https://docs.qmk.fm
// ============================================================

#include QMK_KEYBOARD_H

// ── Layer indices ─────────────────────────────────────────
enum layers {
    _BASE = 0,
    _FN,
    _LAYER2,
    _LAYER3,
};

// ── Keymaps ───────────────────────────────────────────────
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_BASE] = LAYOUT(
        KC_MUTE, KC_BTN3,
        KC_NUM, KC_PSLS, KC_PAST, KC_PMNS,
        KC_P7, KC_P8, KC_P9, KC_PPLS,
        KC_P4, KC_P5, KC_P6,
        KC_P1, KC_P2, KC_P3, KC_PENT,
        KC_P0,           KC_PDOT
    ),

    [_FN] = LAYOUT(
        KC_TRNS, KC_TRNS,
        MO(1), KC_F1, KC_F2, RGB_TOG,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    ),

    [_LAYER2] = LAYOUT(
        KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    ),

    [_LAYER3] = LAYOUT(
        KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    )
};


#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [_BASE] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(MS_WHLU, MS_WHLD) },
    [_FN] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
    [_LAYER2] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
    [_LAYER3] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) }
};
#endif









// ── System Monitor via RAW HID ──────────────────────────
static uint8_t sm_cpu = 0;
static uint8_t sm_ram = 0;
static uint8_t sm_gpu = 0;
static bool    sm_valid = false;
static uint32_t sm_last_rx = 0;

#define HID_CMD_SYSMON 0x03

void raw_hid_receive(uint8_t *data, uint8_t length) {
    if (length < 4) return;
    if (data[0] == HID_CMD_SYSMON) {
        sm_cpu = data[1] > 100 ? 100 : data[1];
        sm_ram = data[2] > 100 ? 100 : data[2];
        sm_gpu = data[3] > 100 ? 100 : data[3];
        sm_valid = true;
        sm_last_rx = timer_read32();
    }
}

// Draw a bar frame + fill at pixel y (6px tall, 84px wide, x=20..103)
static void draw_sm_bar(uint8_t y, uint8_t pct) {
    if (pct > 100) pct = 100;
    const uint8_t x0 = 20;
    const uint8_t x1 = 103;
    // Frame (top/bottom)
    for (uint8_t x = x0; x <= x1; x++) {
        oled_write_pixel(x, y,     true);
        oled_write_pixel(x, y + 5, true);
    }
    // Frame (left/right)
    for (uint8_t j = 1; j < 5; j++) {
        oled_write_pixel(x0, y + j, true);
        oled_write_pixel(x1, y + j, true);
    }
    // Fill (inside 82px, so 1 fill unit ≈ 0.82 pct)
    uint8_t fill = (uint8_t)((uint16_t)(x1 - x0 - 2) * pct / 100);
    for (uint8_t i = 0; i < fill; i++) {
        for (uint8_t j = 0; j < 4; j++) {
            oled_write_pixel(x0 + 1 + i, y + 1 + j, true);
        }
    }
}

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    return OLED_ROTATION_0;
}

bool oled_task_user(void) {

    // System monitor: 3 horizontal bars (CPU/RAM/GPU) + labels + percentages
    oled_clear();
    // Header
    oled_set_cursor(0, 0);
    oled_write_P(PSTR("SYSMON"), true);

    if (!sm_valid) {
        oled_set_cursor(8, 0);
        oled_write_P(PSTR("waiting..."), false);
        oled_set_cursor(0, 2);
        oled_write_P(PSTR("Run companion app"), false);
        return false;
    }

    char pct_str[5];

    // Row 1 — CPU
    oled_set_cursor(0, 1);
    oled_write_P(PSTR("CPU"), false);
    draw_sm_bar(9, sm_cpu);
    snprintf(pct_str, sizeof(pct_str), "%3d", sm_cpu);
    oled_set_cursor(18, 1);
    oled_write(pct_str, false);

    // Row 2 — RAM
    oled_set_cursor(0, 2);
    oled_write_P(PSTR("RAM"), false);
    draw_sm_bar(17, sm_ram);
    snprintf(pct_str, sizeof(pct_str), "%3d", sm_ram);
    oled_set_cursor(18, 2);
    oled_write(pct_str, false);

    // Row 3 — GPU
    oled_set_cursor(0, 3);
    oled_write_P(PSTR("GPU"), false);
    draw_sm_bar(25, sm_gpu);
    snprintf(pct_str, sizeof(pct_str), "%3d", sm_gpu);
    oled_set_cursor(18, 3);
    oled_write(pct_str, false);

    return false; // true = let board render default dashboard, false = we handled it ourselves
}


