// ============================================================
// Candypad QMK Keymap — generated by Candypad Configurator
// Flash with:  qmk compile -kb binepad/candypad -km my_keymap
// Docs: https://docs.qmk.fm
// ============================================================

#include QMK_KEYBOARD_H

// ── Layer indices ─────────────────────────────────────────
enum layers {
    _BASE = 0,
    _FN,
    _LAYER2,
    _LAYER3,
};

// ── Keymaps ───────────────────────────────────────────────
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_BASE] = LAYOUT(
        KC_MUTE, KC_BTN3,
        KC_NUM, KC_PSLS, KC_PAST, KC_PMNS,
        KC_P7, KC_P8, KC_P9, KC_PPLS,
        KC_P4, KC_P5, KC_P6,
        KC_P1, KC_P2, KC_P3, KC_PENT,
        KC_P0,           KC_PDOT
    ),

    [_FN] = LAYOUT(
        KC_TRNS, KC_TRNS,
        MO(1), KC_F1, KC_F2, RGB_TOG,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    ),

    [_LAYER2] = LAYOUT(
        KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    ),

    [_LAYER3] = LAYOUT(
        KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS,           KC_TRNS
    )
};


#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [_BASE] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU), ENCODER_CCW_CW(MS_WHLU, MS_WHLD) },
    [_FN] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
    [_LAYER2] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
    [_LAYER3] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS), ENCODER_CCW_CW(KC_TRNS, KC_TRNS) }
};
#endif




static uint16_t key_press_counts[MATRIX_ROWS][MATRIX_COLS] = {0};
static uint16_t max_press_count = 1;



oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    return OLED_ROTATION_0;
}

bool oled_task_user(void) {

    // Heatmap visualization — full screen
    oled_set_cursor(0, 0);
    oled_write_P(PSTR("KEY HEATMAP"), true);
    oled_set_cursor(0, 1);
    oled_write_P(PSTR("Per-column presses:"), false);
    oled_set_cursor(0, 2);
    for (uint8_t c = 0; c < MATRIX_COLS; c++) {
        uint16_t col_total = 0;
        for (uint8_t r = 0; r < MATRIX_ROWS; r++) {
            col_total += key_press_counts[r][c];
        }
        uint8_t bar = (col_total * 8) / (max_press_count > 0 ? max_press_count * MATRIX_ROWS : 1);
        if (bar > 8) bar = 8;
        oled_write_char('0' + bar, col_total > 0);
        oled_write_char(' ', false);
    }
    oled_set_cursor(0, 3);
    char total_str[12];
    uint32_t total = 0;
    for (uint8_t r = 0; r < MATRIX_ROWS; r++)
        for (uint8_t c = 0; c < MATRIX_COLS; c++)
            total += key_press_counts[r][c];
    snprintf(total_str, sizeof(total_str), "TOTAL:%lu", (unsigned long)total);
    oled_write(total_str, false);

    return false; // true = let board render default dashboard, false = we handled it ourselves
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (record->event.pressed) {
        uint8_t row = record->event.key.row;
        uint8_t col = record->event.key.col;
        key_press_counts[row][col]++;
        if (key_press_counts[row][col] > max_press_count) {
            max_press_count = key_press_counts[row][col];
        }
    }
    return true;
}


